version: '3.8'

services:
  python_service:
    build:
      context: .  # Set the context to the current folder (docker)
      dockerfile: DockerFile.python  # Path to the Dockerfile in the current folder
    container_name: python_container
    image: python_image
    networks:
      - scriptorium_network
    tty: true  # Keeps the container running
    deploy:
      resources:
        limits:
          memory: 512m  # Set memory limit to 512 MB

  javascript_service:
    build:
      context: .  # Set the context to the current folder (docker)
      dockerfile: DockerFile.javascript  # Path to the Dockerfile in the current folder
    container_name: javascript_container
    image: javascript_image
    networks:
      - scriptorium_network
    tty: true  # Keeps the container running
    deploy:
      resources:
        limits:
          memory: 512m  # Set memory limit to 512 MB

  java_service:
    build:
      context: .  # Set the context to the current folder (docker)
      dockerfile: DockerFile.java  # Path to the Dockerfile in the current folder (assuming it's named DockerFile.java)
    container_name: java_container
    image: java_image
    networks:
      - scriptorium_network
    tty: true  # Keeps the container running
    deploy:
      resources:
        limits:
          memory: 512m  # Set memory limit to 512 MB

  c_service:
    build:
      context: .  # Set the context to the current folder (docker)
      dockerfile: DockerFile.c  # Path to the Dockerfile for C
    container_name: c_container
    image: c_image
    networks:
      - scriptorium_network
    tty: true  # Keeps the container running
    deploy:
      resources:
        limits:
          memory: 512m  # Set memory limit to 512 MB

networks:
  scriptorium_network:
    driver: bridge