version: '3.8'

services:
  python_service:
    build:
      context: .  # Set the context to the current folder (docker)
      dockerfile: DockerFilePython  # Path to the Dockerfile in the current folder
    container_name: python_container
    image: python_image
    networks:
      - scriptorium_network
    tty: true  # Keeps the container running
    deploy:
      resources:
        limits:
          memory: 512m  # Set memory limit to 512 MB

  javascript_service:
    build:
      context: .  # Set the context to the current folder (docker)
      dockerfile: DockerFileJavascript  # Path to the Dockerfile in the current folder
    container_name: javascript_container
    image: javascript_image
    networks:
      - scriptorium_network
    tty: true  # Keeps the container running
    deploy:
      resources:
        limits:
          memory: 512m  # Set memory limit to 512 MB

  java_service:
    build:
      context: .  # Set the context to the current folder (docker)
      dockerfile: DockerFileJava  # Path to the Dockerfile in the current folder
    container_name: java_container
    image: java_image
    networks:
      - scriptorium_network
    tty: true  # Keeps the container running
    deploy:
      resources:
        limits:
          memory: 512m  # Set memory limit to 512 MB

  c_service:
    build:
      context: .  # Set the context to the current folder (docker)
      dockerfile: DockerFileC  # Path to the Dockerfile for C
    container_name: c_container
    image: c_image
    networks:
      - scriptorium_network
    tty: true  # Keeps the container running
    deploy:
      resources:
        limits:
          memory: 512m  # Set memory limit to 512 MB

  cpp_service:
    build:
      context: .  # Set the context to the current folder (docker)
      dockerfile: DockerFileCpp  # Path to the Dockerfile for C++
    container_name: cpp_container
    image: cpp_image
    networks:
      - scriptorium_network
    tty: true  # Keeps the container running
    deploy:
      resources:
        limits:
          memory: 512m  # Set memory limit to 512 MB

  ruby_service:
    build:
      context: .  # Set the context to the current folder (docker)
      dockerfile: DockerFileRuby  # Path to the Dockerfile for Ruby
    container_name: ruby_container
    image: ruby_image
    networks:
      - scriptorium_network
    tty: true  # Keeps the container running
    deploy:
      resources:
        limits:
          memory: 512m  # Set memory limit to 512 MB

networks:
  scriptorium_network:
    driver: bridge
